group: travis_latest
language: python
cache: pip
matrix:
    include:
      - python: 3.6
        dist: bionic
      - python: 3.7
        dist: bionic
      - python: 3.8
        dist: bionic
      - python: 3.9-dev
        dist: bionic
      - python: nightly
        dist: bionic
      - python: pypy3
        dist: bionic
    allow_failures:
        - python: 3.9-dev
        - python: nightly
before_install:
  - sudo apt-get -y install mandoc
install:
  - pip install -U -r requirements.txt
  - pip install -U -r requirements-test.txt
  - pip list
script:
  - pyflakes --version && pyflakes *.py
  - pytest --version && pytest tests/
  - mandoc -T lint man/man1/htcrystalball.1
